version: "3.9"


services:
  traefik:
    image: "traefik:v2.5"
    container_name: "traefik"
    command:
      # - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  be-auth:
    build:
      context: ./be-auth
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.be-auth.rule=Host(`auth.localhost`)"
      - "traefik.http.routers.be-auth.entrypoints=web"
      - "traefik.http.services.be-auth.loadbalancer.server.port=80"

  fe:
    build:
      context: ./fe
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fe.rule=Host(`localhost`)"
      - "traefik.http.routers.fe.entrypoints=web"

  db:
    image: postgres
    environment:
      - POSTGRES_DB=auth
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
    volumes:
      - db-data:/var/lib/postgresql/data


volumes:
  db-data:
    driver: local
